name: Ethereum, NEAR, and STARKNET Auto Commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write # Grants permissions to write to the repo

jobs:
  ethereum_auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ethereum script
        run: |
          chmod +x ethereum.sh
          ./ethereum.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Generate random commit message
        id: random_commit_message
        run: |
          arr=("🚀 Updated contract" "🔧 Fixed bug" "📈 Added new feature" "🌟 Implemented improvement")
          index=$(( RANDOM % ${#arr[@]} ))
          echo "::set-output name=message::${arr[$index]}"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(echo "${{ steps.random_commit_message.outputs.message }}")"

      - name: Push changes
        run: |
          git push origin master

  near_auto_commit:
    runs-on: ubuntu-latest
    needs: ethereum_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run NEAR script
        run: |
          chmod +x near.sh
          ./near.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Generate random commit message
        id: random_commit_message
        run: |
          arr=("🚀 Updated contract" "🔧 Fixed bug" "📈 Added new feature" "🌟 Implemented improvement")
          index=$(( RANDOM % ${#arr[@]} ))
          echo "::set-output name=message::${arr[$index]}"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(echo "${{ steps.random_commit_message.outputs.message }}")"

      - name: Push changes
        run: |
          git push origin master

  starknet_auto_commit:
    runs-on: ubuntu-latest
    needs: near_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run STARKNET script
        run: |
          chmod +x starknet.sh
          ./starknet.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Generate random commit message
        id: random_commit_message
        run: |
          arr=("🚀 Updated contract" "🔧 Fixed bug" "📈 Added new feature" "🌟 Implemented improvement")
          index=$(( RANDOM % ${#arr[@]} ))
          echo "::set-output name=message::${arr[$index]}"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(echo "${{ steps.random_commit_message.outputs.message }}")"

      - name: Push changes
        run: |
          git push origin master
