name: Ethereum, NEAR, StarkNet, and Axelar Auto Commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write # Grants permissions to write to the repo

jobs:
  ethereum_auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ethereum script
        run: |
          chmod +x ethereum.sh
          ./ethereum.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Auto commit changes for Ethereum network"

      - name: Push changes
        run: |
          git push origin master

  near_auto_commit:
    runs-on: ubuntu-latest
    needs: ethereum_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run NEAR script
        run: |
          chmod +x near.sh
          ./near.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Auto commit changes for NEAR network"

      - name: Push changes
        run: |
          git push origin master

  starknet_auto_commit:
    runs-on: ubuntu-latest
    needs: near_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run StarkNet script
        run: |
          chmod +x starknet.sh
          ./starknet.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Auto commit changes for StarkNet network"

      - name: Push changes
        run: |
          git push origin master

  axelar_auto_commit:
    runs-on: ubuntu-latest
    needs: starknet_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run Axelar script
        run: |
          chmod +x axelar.sh
          ./axelar.sh

      - name: Configure Git identity
        run: |
          git config user.email "rxmxdhxni@gmail.com"
          git config user.name "dante4rt"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Auto commit changes for Axelar network"

      - name: Push changes
        run: |
          git push origin master
